mappings:
  CountryRegionDeliveryModifier: Sunnysideup\EcommerceDelivery\Modifiers\CountryRegionDeliveryModifier
  PickUpOrDeliveryModifier: Sunnysideup\EcommerceDelivery\Modifiers\PickUpOrDeliveryModifier
  PickUpOrDeliveryModifierOptionsRegion: Sunnysideup\EcommerceDelivery\Model\PickUpOrDeliveryModifierOptionsRegion
  PickUpOrDeliveryModifierOptions_WeightBracket: Sunnysideup\EcommerceDelivery\Model\PickUpOrDeliveryModifierOptions_WeightBracket
  PickUpOrDeliveryModifierOptionsCountry: Sunnysideup\EcommerceDelivery\Model\PickUpOrDeliveryModifierOptionsCountry
  PickUpOrDeliveryModifierOptions: Sunnysideup\EcommerceDelivery\Model\PickUpOrDeliveryModifierOptions
  PickUpOrDeliveryModifierOptions_SubTotalBracket: Sunnysideup\EcommerceDelivery\Model\PickUpOrDeliveryModifierOptions_SubTotalBracket
  PickUpOrDeliveryModifier_Form: Sunnysideup\EcommerceDelivery\Forms\PickUpOrDeliveryModifier_Form
