---
Name: ecommerce_delivery_routes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    ecommercedeliverysetoption//$Action/$ID/$OtherID/$Version: Sunnysideup\Ecommerce\Control\OrderModifierFormController
